### ISSUE TITLE
libs.min.js:1 TypeError: Cannot set property project of #<r> which has only a getter

### ISSUE THREAD

**Issue by amolaridas2018** [LearnLib/alex#13] opened 2018-11-12 09:55 UTC
When I am trying to perform inspect element on an action, I am getting the following error in the console and the inspector window does not open

libs.min.js:1 TypeError: Cannot set property project of #<r> which has only a getter
    at r (alex.min.js:1)
    at Object.invoke (libs.min.js:1)
    at $t.instance (libs.min.js:1)
    at W (libs.min.js:1)
    at libs.min.js:1
    at libs.min.js:1
    at o.value (alex.min.js:1)
    at t.value (alex.min.js:1)
    at fn (eval at compile (libs.min.js:1), <anonymous>:4:166)
    at e (libs.min.js:1)

Any ideas how to resolve this issue, please?

**Comment by abainczyk** [comment] 2018-11-13 07:55
Hi, please provide more information to this issue, e.g. which version of ALEX and which browser you are using.

**Comment by amolaridas2018** [comment] 2018-11-13 08:32
Hi,

I am using the latest versions of Chrome or Firefox browsers. on a windows 10 64 bit machine. Also downloaded the latest version of Alex software alex-1.0.6.war

thanks

**Comment by amolaridas2018** [comment] 2018-11-30 14:39
@abainczyk any updates on this, please? I have tried again on a different machine and I am experiencing the same issue still

**Comment by abainczyk** [comment] 2018-11-30 16:07
Hi, I am sorry but I still cannot reproduce your issue. Could you also provide a screenshot on where exactly you are clicking on in ALEX so that this error occurs? Does the error affect the functionality of the tool in any way?

**Comment by amolaridas2018** [comment] 2018-11-30 16:12
Hi,

here is the screenshot - clicking the element picker does not open/launch the window to select the web element. The error does prevent selecting the web elements and causes error when executing the test.

![image](https://user-images.githubusercontent.com/44966983/49300615-983c8e80-f4ba-11e8-8acc-2bc317b6bef5.png)

**Comment by abainczyk** [comment] 2018-11-30 16:18
Oh... based on your initial bug description I somehow thought of something completely different. Okay, I will look into it.

**Comment by abainczyk** [comment] 2018-12-03 11:02
Hi, I found the reason for the issue and will publish a minor release of ALEX this week that contains a fix for the error.

**Comment by amolaridas2018** [comment] 2018-12-03 11:03
excellent. thank you. just drop a comment here for my attention. ta

**Comment by abainczyk** [comment] 2018-12-05 11:32
Hi, I just released version 1.6.1 which you can find on the GitHub release page. Please provide feedback if the fix works for you so you can close the issue. Simply replace the old war archive with the new one and do not delete the *target* folder.

**Comment by abainczyk** [comment] 2018-12-05 11:41
Also please clear your browser cache with the new version so that the changes are visible.

**Closed** 2018-12-06 13:51 UTC
