### ISSUE TITLE
Symbol name must be unique

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/alex#3] opened 2016-10-27 07:22 UTC
We gave a tutorial on ALEX at the BSR winter school. Some issues popped up.

When making a reset symbol, and adding actions some people ran into the problem that the actions cannot be saved as the symbol must be a unique name. But it actually has a unique name, so that's a bit weird. We could not really reproduce it, although we had it once too.

**Comment by abainczyk** [comment] 2016-11-05 07:27
I can't reproduce this issue. Please provide an exact use case where the application behaves like you described. I close this issue for now.

**Closed by abainczyk** 2016-11-05 07:27 UTC
