### ISSUE TITLE
JNA error

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/alex#5] opened 2016-10-27 07:45 UTC
One of the students found this error while running ALEX:

> The word could not be executed. java.lang.Error: There is an incompatible JNA natice library installed on this system [...] To resolve this issue you may do one of the following: - remove or uninstall the offending library - set the system propery jna.nosys=true - set jna.boot.library.path to include the path to the version of the jnidispatch library included with the JNA jar file you are using.

He added `-Djna.nosys=true` when running ALEX. This seemed to fix it, and it worked well afterwards.

**Comment by abainczyk** [comment] 2016-10-27 07:57
We never had this kind of exception on any of our test machines. Because it is a JNA error, I assume it has something to do with Selenium and the web driver executable the student was using and the version of the JRE/JDK. Do you have any more information on that?

**Comment by Jaxan** [comment] 2016-10-27 22:38
Here are some version numbers. He uses the chrome driver from the Alex tutorial. 

- Windows 8.1 Enterprise
- Java x64 version 1.8.0_45
- Chrome 54.0.2840.71 m
- Chrome Driver 2.25 win32

**Comment by abainczyk** [comment] 2017-10-18 08:42
We could not reproduce this error and it never occured on our testing machines ever since. So I close this issue.

**Closed by abainczyk** 2017-10-18 08:42 UTC
